### ISSUE TITLE
This is great. Expands my understanding of thinking about testing. Love it!

### ISSUE THREAD

**Issue by richorrichard** [ugitch/js-array-methods#1]
I really appreciate that I've been able to see your Method Function interpretations during my learning – seeing a test like this is helping me to reframe my concepts of how to approach the context of a logical step, and it's helping me to expand my scope of observation. I'll keep checking my repo against yours as I progress but I love it. Thanks for the inspiration!

https://github.com/ugitch/js-array-methods/blob/231e83914d668f4cac6a2d3460eed1edfc4b1f16/iterator/every.html#L116

**Comment by ugitch** [comment]
Thank you, Richard!

I guess I haven't been hurrying too much, taking enough time for it to
sink in, naming the tests appropriately to make them seem in
correlation with the tested function.

I'm truly glad it helped you in your thinking and approach and that it
inspired you!

2019-10-17 23:55 GMT+02:00, Richard Sherman <notifications@github.com>:
